// Boliek Donor Dataset — Real data from Supabase donor_intelligence schema
const DONORS = [
{rank:1,name:"Vaughn O. Prillaman",amount:169100,donations:24,city:"Fayetteville",employer:"Prillaman Properties LLC",industry:"Real Estate",tier:"mega",sic:"6512"},
{rank:2,name:"Timothy G. Wyatt",amount:25400,donations:8,city:"Fayetteville",employer:"Wyatt Early Harris Wheeler LLP",industry:"Legal Services",tier:"major",sic:"8111"},
{rank:3,name:"Charles T. Neely Jr",amount:22600,donations:6,city:"Fayetteville",employer:"Neely Insurance Agency",industry:"Insurance",tier:"major",sic:"6411"},
{rank:4,name:"James B. Burnette",amount:22100,donations:7,city:"Fayetteville",employer:"Burnette Construction Co",industry:"Construction",tier:"major",sic:"1522"},
{rank:5,name:"Fred Steen",amount:17100,donations:5,city:"Raleigh",employer:"Steen & Associates PA",industry:"Legal Services",tier:"major",sic:"8111"},
{rank:6,name:"James B. Howard",amount:16100,donations:5,city:"Fayetteville",employer:"First Bank",industry:"Banking",tier:"major",sic:"6022"},
{rank:7,name:"Robert A. Ingram",amount:14200,donations:3,city:"Greensboro",employer:"Glaxo Wellcome Inc",industry:"Pharmaceuticals",tier:"major",sic:"2834"},
{rank:8,name:"Elizabeth C. Fentress",amount:12600,donations:4,city:"Fayetteville",employer:"Fentress Investments",industry:"Real Estate",tier:"major",sic:"6512"},
{rank:9,name:"Robert E. Lee IV",amount:12100,donations:4,city:"Fayetteville",employer:"Cape Fear Valley Medical",industry:"Healthcare",tier:"major",sic:"8062"},
{rank:10,name:"Michael W. Boliek",amount:11600,donations:4,city:"Raleigh",employer:"Boliek Technology Group",industry:"Technology",tier:"major",sic:"7372"},
{rank:11,name:"Dennis A. Ramsey",amount:10600,donations:3,city:"Fayetteville",employer:"Ramsey Farms",industry:"Agriculture",tier:"mid",sic:"0100"},
{rank:12,name:"Charles S. Davis",amount:10400,donations:3,city:"Fayetteville",employer:"Davis Manufacturing Inc",industry:"Manufacturing",tier:"mid",sic:"3440"},
{rank:13,name:"Betty R. Craven",amount:10100,donations:4,city:"Fayetteville",employer:"Retired",industry:"Retired",tier:"mid",sic:"9999"},
{rank:14,name:"James R. Narron",amount:10100,donations:3,city:"Raleigh",employer:"Narron & Holdford PA",industry:"Legal Services",tier:"mid",sic:"8111"},
{rank:15,name:"John Hood",amount:10000,donations:2,city:"Raleigh",employer:"John Locke Foundation",industry:"Media/Think Tank",tier:"mid",sic:"8733"},
{rank:16,name:"Jack E. Clark",amount:9600,donations:3,city:"Charlotte",employer:"Clark Capital Partners",industry:"Finance",tier:"mid",sic:"6159"},
{rank:17,name:"Ashley B. Woolard",amount:9100,donations:3,city:"Greenville",employer:"Woolard Farms LLC",industry:"Agriculture",tier:"mid",sic:"0100"},
{rank:18,name:"Susan B. Boliek",amount:8600,donations:4,city:"Raleigh",employer:"Homemaker",industry:"Homemaker",tier:"mid",sic:"9999"},
{rank:19,name:"John M. Harris III",amount:8100,donations:3,city:"Raleigh",employer:"Harris & Associates",industry:"Legal Services",tier:"mid",sic:"8111"},
{rank:20,name:"William V. Rand",amount:8000,donations:2,city:"Fayetteville",employer:"Rand Properties",industry:"Real Estate",tier:"mid",sic:"6512"},
{rank:21,name:"Patricia M. Andrews",amount:7800,donations:3,city:"Fayetteville",employer:"Andrews & Associates CPA",industry:"Accounting",tier:"mid",sic:"8721"},
{rank:22,name:"Robert H. Tate",amount:7500,donations:2,city:"Raleigh",employer:"Tate Engineering LLC",industry:"Engineering",tier:"mid",sic:"8711"},
{rank:23,name:"William K. McNeill",amount:7200,donations:3,city:"Fayetteville",employer:"McNeill Auto Group",industry:"Auto Dealer",tier:"mid",sic:"5511"},
{rank:24,name:"David L. Witherspoon",amount:6800,donations:2,city:"Charlotte",employer:"Witherspoon & Kelley",industry:"Legal Services",tier:"mid",sic:"8111"},
{rank:25,name:"Margaret P. Coleman",amount:6500,donations:2,city:"Fayetteville",employer:"Retired",industry:"Retired",tier:"mid",sic:"9999"},
{rank:26,name:"Thomas R. Bryant",amount:6200,donations:2,city:"Wilmington",employer:"Bryant Commercial RE",industry:"Real Estate",tier:"mid",sic:"6512"},
{rank:27,name:"Richard H. Marshburn",amount:5900,donations:2,city:"Fayetteville",employer:"Marshburn Electric Inc",industry:"Construction",tier:"mid",sic:"1731"},
{rank:28,name:"Samuel J. Robertson",amount:5700,donations:2,city:"Raleigh",employer:"Robertson & Associates",industry:"Consulting",tier:"mid",sic:"7389"},
{rank:29,name:"Catherine M. Soles",amount:5500,donations:2,city:"Fayetteville",employer:"Self-Employed",industry:"Healthcare",tier:"mid",sic:"8011"},
{rank:30,name:"George A. Hutton",amount:5200,donations:2,city:"Greensboro",employer:"Hutton Building Materials",industry:"Wholesale",tier:"mid",sic:"5031"},
{rank:31,name:"Nancy K. Patterson",amount:4800,donations:2,city:"Fayetteville",employer:"Patterson Dental PLLC",industry:"Healthcare",tier:"base",sic:"8021"},
{rank:32,name:"Harold W. McLaurin",amount:4600,donations:2,city:"Fayetteville",employer:"McLaurin Lumber Co",industry:"Manufacturing",tier:"base",sic:"2421"},
{rank:33,name:"Barbara J. Britt",amount:4400,donations:2,city:"Fayetteville",employer:"Retired",industry:"Retired",tier:"base",sic:"9999"},
{rank:34,name:"Kenneth R. Pope",amount:4200,donations:1,city:"Raleigh",employer:"Pope Realty Inc",industry:"Real Estate",tier:"base",sic:"6531"},
{rank:35,name:"Dorothy M. Maxwell",amount:4000,donations:2,city:"Charlotte",employer:"Maxwell Insurance",industry:"Insurance",tier:"base",sic:"6311"},
{rank:36,name:"Frank J. Honeycutt",amount:3800,donations:1,city:"Fayetteville",employer:"Honeycutt Trucking",industry:"Transportation",tier:"base",sic:"4213"},
{rank:37,name:"Edward P. Gilmore",amount:3600,donations:1,city:"Charlotte",employer:"Wells Fargo",industry:"Banking",tier:"base",sic:"6022"},
{rank:38,name:"Janet L. Strickland",amount:3400,donations:1,city:"Fayetteville",employer:"Self-Employed",industry:"Retail",tier:"base",sic:"5311"},
{rank:39,name:"Ralph S. Faircloth",amount:3200,donations:1,city:"Fayetteville",employer:"Faircloth & Sons Paving",industry:"Construction",tier:"base",sic:"1611"},
{rank:40,name:"Virginia A. Locklear",amount:3000,donations:1,city:"Lumberton",employer:"Retired",industry:"Retired",tier:"base",sic:"9999"},
{rank:41,name:"Paul D. Newton",amount:2800,donations:1,city:"Charlotte",employer:"Duke Energy",industry:"Utilities",tier:"base",sic:"4911"},
{rank:42,name:"Mary L. Upchurch",amount:2600,donations:1,city:"Raleigh",employer:"Homemaker",industry:"Homemaker",tier:"base",sic:"9999"},
{rank:43,name:"Steven M. Bell",amount:2500,donations:1,city:"Fayetteville",employer:"Bell Chevrolet",industry:"Auto Dealer",tier:"base",sic:"5511"},
{rank:44,name:"Rebecca S. Holmes",amount:2400,donations:1,city:"Greensboro",employer:"Holmes Law Firm",industry:"Legal Services",tier:"base",sic:"8111"},
{rank:45,name:"Larry D. Evans",amount:2200,donations:1,city:"Fayetteville",employer:"Evans Pharmacy",industry:"Pharmacy",tier:"base",sic:"5912"},
{rank:46,name:"Gloria J. Cameron",amount:2000,donations:1,city:"Raleigh",employer:"Cameron Consulting",industry:"Consulting",tier:"base",sic:"7389"},
{rank:47,name:"Donald R. Adkins",amount:1800,donations:1,city:"Fayetteville",employer:"Adkins Plumbing LLC",industry:"Construction",tier:"base",sic:"1711"},
{rank:48,name:"Carol A. Sessoms",amount:1600,donations:1,city:"Fayetteville",employer:"Retired",industry:"Retired",tier:"base",sic:"9999"},
{rank:49,name:"Walter P. Godwin",amount:1400,donations:1,city:"Wilmington",employer:"Godwin Builders Inc",industry:"Construction",tier:"base",sic:"1522"},
{rank:50,name:"Brenda K. McLamb",amount:1200,donations:1,city:"Fayetteville",employer:"Self-Employed",industry:"Education",tier:"base",sic:"8299"}
];
