"""Test: AI content surfaces disclosure when state law requires."""
from __future__ import annotations
import sys, unittest
from pathlib import Path
from unittest.mock import patch

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "ecosystems"))

import ecosystem_19_social_media as e19


class AIDisclosureGateTest(unittest.TestCase):
    def setUp(self):
        self._patcher = patch.object(e19, "_log_compliance_decision")
        self._patcher.start()

    def tearDown(self):
        self._patcher.stop()

    def test_non_ai_content_skips_gate(self):
        result = e19.check_state_ai_disclosure(
            {"ai_generated": False, "body": "Human-written"}, "CA"
        )
        self.assertTrue(result["allow"])
        self.assertEqual(result["reason"], "not_ai_generated")

    def test_ai_content_no_state_rule_allowed(self):
        # ND has no AI law in our table.
        result = e19.check_state_ai_disclosure(
            {"ai_generated": True, "body": "AI body"}, "ND"
        )
        self.assertTrue(result["allow"])
        self.assertEqual(result["reason"], "no_state_rule")

    def test_ai_content_in_ca_without_disclosure_blocked(self):
        result = e19.check_state_ai_disclosure(
            {"ai_generated": True, "body": "Vote!"}, "CA"
        )
        self.assertFalse(result["allow"])
        self.assertIn("ca", result["reason"])

    def test_ai_content_in_ca_with_disclosure_allowed(self):
        result = e19.check_state_ai_disclosure(
            {"ai_generated": True,
             "body": "Vote! This message was AI-generated for clarity.",
            }, "CA"
        )
        self.assertTrue(result["allow"])

    def test_ai_content_in_tx_blocked_without_disclosure(self):
        result = e19.check_state_ai_disclosure(
            {"ai_generated": True, "body": "Vote!"}, "TX"
        )
        self.assertFalse(result["allow"])
        self.assertIn("tx", result["reason"])

    def test_disclosure_in_separate_field_allowed(self):
        result = e19.check_state_ai_disclosure(
            {"ai_generated": True, "body": "Vote!",
             "disclosure": "Generated by AI; reviewed by candidate."},
            "MI"
        )
        self.assertTrue(result["allow"])


if __name__ == "__main__":
    unittest.main()
