-- Migration 096: HOLD — DO NOT EXECUTE
-- Written: April 8, 2026 | Revised: April 8, 2026
-- 
-- ORIGINAL INTENT: Purge memo rows from fec_donations
-- 
-- WHY THIS IS WRONG:
-- The 333,830 is_memo=true / receipt_type=15J rows in the Trump 2022-2026 file
-- are JFC EARMARKS — real NC individuals (John Willauer, Brenda Lemmond, etc.)
-- donating through joint fundraising committees (NEVER SURRENDER INC., SAVE AMERICA PAC)
-- with money earmarked for Trump. These ARE individual donors. Deleting them would 
-- wipe the entire NC small-dollar Trump donor universe.
--
-- FEC receipt_type reference:
--   15J = Earmarked contribution (JFC conduit) → KEEP
--   15E = Earmarked contribution               → KEEP
--   15  = Regular contribution                 → KEEP
--   24I = Independent expenditure against      → Review
--   24T = Independent expenditure for          → Review
--
-- STATUS: Migration cancelled. No purge needed.
-- fec_donations rows are valid as-is.
-- 
-- If specific receipt_types need separate handling in the future,
-- write a new targeted migration after inspecting each type.
