-- 098_UNIFIED_CONTACTS_STUB_AND_DATATRUST_BACKFILL.sql
-- Prerequisite: 097_INTEGRATION_DATATRUST_CONTACT_LINK.sql (integration.datatrust_contact_link).
--
-- 1) Minimal public.unified_contacts so datatrust_matching_procedures can be created on DBs that
--    only have nc_datatrust today. Skipped if the table already exists (any shape).
-- 2) Optional backfill from public.datatrust_profiles when that legacy table exists.
--
-- Run: psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f database/migrations/098_UNIFIED_CONTACTS_STUB_AND_DATATRUST_BACKFILL.sql

CREATE TABLE IF NOT EXISTS public.unified_contacts (
  contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mobile_phone TEXT,
  home_phone TEXT,
  email TEXT,
  last_name_clean TEXT,
  first_name_clean TEXT,
  zip_code TEXT,
  city TEXT,
  county TEXT,
  state TEXT,
  street_line_1 TEXT,
  donor_grade TEXT,
  volunteer_status TEXT,
  total_donations_aggregated NUMERIC DEFAULT 0,
  engagement_score INTEGER DEFAULT 0,
  custom_fields JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.unified_contacts IS
  'CRM / contact hub. Created as minimal stub when missing; safe to replace with full schema via later migration.';

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'datatrust_profiles'
  ) THEN
    INSERT INTO integration.datatrust_contact_link (
      rncid, contact_id, synced_to_unified_contacts, sync_date, updated_at
    )
    SELECT
      trim(dp.rnc_id::text),
      dp.contact_id,
      COALESCE(dp.synced_to_unified_contacts, false),
      dp.sync_date,
      now()
    FROM public.datatrust_profiles dp
    INNER JOIN public.nc_datatrust dt ON trim(dt.rncid::text) = trim(dp.rnc_id::text)
    WHERE trim(COALESCE(dp.rnc_id::text, '')) <> ''
      AND dp.contact_id IS NOT NULL
    ON CONFLICT (rncid) DO UPDATE SET
      contact_id = COALESCE(integration.datatrust_contact_link.contact_id, EXCLUDED.contact_id),
      synced_to_unified_contacts =
        integration.datatrust_contact_link.synced_to_unified_contacts
        OR EXCLUDED.synced_to_unified_contacts,
      sync_date = COALESCE(EXCLUDED.sync_date, integration.datatrust_contact_link.sync_date),
      updated_at = now();
    RAISE NOTICE 'Backfilled integration.datatrust_contact_link from public.datatrust_profiles';
  END IF;
END $$;
